version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=webserver
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=webdb 
  
  webserver:
    build: ./0
    ports:
      - '5000:5000'
    depends_on:
      - 'postgres'


